### PR TITLE
Proposed figures for vignette (issue #12)

### LINKED ISSUE #12: Diagrams for the vignettes
It would be nice to have some diagrams for the vignettes (see https://github.com/ropensci/onboarding/issues/114#issuecomment-318153231)

### PR DESCRIPTION
**Pull request by superjai**
Hello! Jai Ranganathan here. I am an ecologist and a big fan of rOpenSci. I thought I would try to help out and I heard from Stefanie Butland that the lack of figures in the vignettes for this package was a longstanding issue (issue #12 ) . I thought I would pitch in. This is my first time contributing to a github repo for which I didn't have write access, so I apologize in advance for any errors that I have made.

I created two figures for the vignette cyphr.Rmd, using the fantastic imagery in the github package [pointblank](https://github.com/rich-iannone/pointblank) as an inspiration. I will be the first to say that I am not a graphic designer, so please do let me know how they could be improved. If this seems to be roughly the right track, I will go ahead and create figures for the other vignette. 

Thanks!
Jai

Fixes #12

### CODE REVIEW

**Comment by richfitz** [comment]
Fixes #12

**Review by richfitz — CHANGES_REQUESTED** [review]
Hi @superjai, and thanks for your contribution!

This is great, thank you. I have a couple of (hopefully small) requests:

* Can you use colour+pattern to help distinguish between alice and bob's private and public keys (e.g., one colour for both of alice's, one texture for both the public keys)
* If you have original svg artwork for this could you please add them to the vignettes directory too, along with instructions for generating the .png from the source image (they'll need to be added to Rbuildignore too, but if you give me push access to your PR I can take care of that)
* Can you please add yourself to the Authors@R section of the DESCRIPTION (see [here](https://github.com/ropensci/jsonvalidate/blob/master/DESCRIPTION#L4-L10) for a template)
* Can you increase the version number to 1.1.1

**Comment by stefaniebutland** [comment]
Thank you @superjai!

**Comment by superjai** [comment]
Hi @richfitz! I am glad that you find these figures to be useful. Let me address your points:

- Instead of altering the pattern between public and private keys (which I couldn't get to look right), I instead changed the shape of public keys. What do you think?

- The svg files were added. I created the figures in Inkscape, with the svg files being the source images and the png files being an exported version. You should be able to view svg files in a browser, but for some reason the formatting of the svg files is a bit off (when viewed in Chrome). Additionally, I just invited you to the repo.

- The DESCRIPTION file was changed.

**Review by richfitz — CHANGES_REQUESTED** [review]
Thanks - the change in shape looks great. If you could extend that to cover the pair (which has the same style keys) in the bottom two panels of `vignettes/asymmetric.png` that would be great, then I can merge this (and it will appear ~immediately on the docs [here](https://docs.ropensci.org/cyphr/articles/cyphr.html)

**Comment by superjai** [comment]
Done!

**Review by richfitz — APPROVED** [review]
Thanks - I really appreciate this :)

**Pull request merged**
